# Generated by Django 4.2 on 2023-05-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_libro', models.CharField(max_length=200)),
                ('agno_publicacion', models.DateField()),
            ],
        ),
    ]
